---
- name: Provision On Demand Runners
  hosts: localhost

  vars_files:
    - vars/config.yml

  pre_tasks:
    - name: Initialize Config Variables
      include_vars: vars/config.yml

    - name: Set Resource Class Name
      set_fact:
        RESOURCE_CLASS: "{{ lookup('env', 'CIRCLE_PROJECT_REPONAME') }}-{{ lookup('env', 'CIRCLE_SHA1') }}"
      when: (RESOURCE_CLASS_CREATION | bool == true or RUNNER_TOKEN_CREATION | bool == true) and (RESOURCE_CLASS == '' or RESOURCE_CLASS is not defined)

  tasks:
    - name: Deploy On Demand Runners for given cloud provider
      include_tasks: tasks/provision.yml