RESOURCE_CLASS_CREATION: true
RUNNER_TOKEN_CREATION: true

# Only Set Auth Token if RUNNER_TOKEN_CREATION is False
#AUTH_TOKEN:

NAMESPACE: 
#RESOURCE_CLASS:
#RESOURCE_CLASS_DESCRIPTION:

API_TOKEN:

target_hosts: 

SSH_KEY_NAME:
VPC_ID: 
INSTANCE_TYPE: "t2.micro"
SECURITY_GROUP: "sg-06aabc9ff843b02b8"
AMI_ID: "ami-0e963171450730a53"
REGION: "us-east-2"

# 10 Seconds between each retry
# 10 sec * 18 = 3 Mins
UNTIL_RETRIES_RUNNERS: "18"

NUMBER_OF_RUNNERS: 2
TEMPLATE_DYNAMIC_INVENTORY: true

CLOUD_PROVIDER: "aws"